const test=require('node:test'),assert=require('node:assert/strict'),C=require('./dist/core.js');
const user={name:'Test Person',school:'Babcock'};
const course=(extra={})=>({code:'ABC101',title:'A course',units:3,day:0,start:'09:00',end:'11:00',room:'',...extra});
test('only full name and the listed schools are required for entry',()=>{assert.deepEqual(C.identity(' Test Person ','Covenant'),{name:'Test Person',school:'Covenant'});for(const school of C.schools)assert(C.identity('Test Person',school));assert.throws(()=>C.identity('A','ABUAD'));assert.throws(()=>C.identity('First','ABUAD'));assert.throws(()=>C.identity('Test Person','Other'));});
test('a new workspace has no invented records and is isolated by identity',()=>{const storage=new Map(),adapter={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};let state=C.load(adapter,user);assert.deepEqual([state.courses,state.tasks,state.results],[[],[],[]]);state=C.course(state,course());C.save(adapter,state);assert.equal(C.load(adapter,user).courses.length,1);assert.equal(C.load(adapter,{name:'Another Person',school:'Babcock'}).courses.length,0);assert.equal(C.load(adapter,{name:'Test Person',school:'ABUAD'}).courses.length,0);});
test('courses reject duplicate codes and overlapping class times',()=>{const state=C.course(C.fresh(user),course());assert.throws(()=>C.course(state,course()),/already added/);assert.throws(()=>C.course(state,course({code:'DEF202',day:0,start:'10:00',end:'12:00'})),/overlaps/);assert.equal(C.course(state,course({code:'DEF202',day:1})).courses.length,2);});
test('tasks require a date and an existing course if linked',()=>{const state=C.course(C.fresh(user),course());assert.throws(()=>C.task(state,{title:'Essay',due:'',courseId:''}),/date/);assert.throws(()=>C.task(state,{title:'Essay',due:'2026-10-01',courseId:'missing'}),/course/);const next=C.task(state,{title:'Essay',due:'2026-10-01',courseId:state.courses[0].id});assert.equal(next.tasks[0].title,'Essay');});
test('results are user-entered and weighted GPA is correct',()=>{let state=C.course(C.fresh(user),course());const first=state.courses[0];state=C.course(state,course({code:'DEF202',day:1,units:2}));const second=state.courses[1];state=C.result(state,{courseId:first.id,score:72});state=C.result(state,{courseId:second.id,score:60});assert.equal(C.gpa(state),4.6);assert.throws(()=>C.result(state,{courseId:first.id,score:90}),/already recorded/);assert.throws(()=>C.result(state,{courseId:second.id,score:101}),/score/);});
test('failed storage writes cannot mutate the saved workspace',()=>{const state=C.fresh(user);assert.throws(()=>C.save({setItem(){throw Error('Full');}},state),/Full/);assert.equal(state.courses.length,0);});
